<?php

return [
    [
        'name' => 'wechat',
        'title' => '微信',
        'type' => 'array',
        'content' => [],
        'value' => [
            'appid' => 'wx54cbea3e9032fe6d',
            'app_id' => 'wx54cbea3e9032fe6d',
            'app_secret' => '644f62eb0be6d9ec9a90c2eb1ebade8d',
            'miniapp_id' => '',
            'mch_id' => '1529035701',
            'key' => '94c8Ab4F56b410bAa6a0597ef6Tb8995',
            'notify_url' => '/addons/epay/api/notifyx/type/wechat',
            'cert_client' => '/epay/certs/apiclient_cert.pem',
            'cert_key' => '/epay/certs/apiclient_key.pem',
            'log' => '0',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '微信参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'alipay',
        'title' => '支付宝',
        'type' => 'array',
        'content' => [],
        'value' => [
            'app_id' => '2021001134694930',
            'notify_url' => '/addons/epay/api/notifyx/type/alipay',
            'return_url' => '/addons/epay/api/returnx/type/alipay',
            'ali_public_key' => 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv9jlLAM4HxeYm5MxQOUnOOgq0/8VVyzDA7z9vIIPAvFGGC7HHdJvci0u/5nQtRBCz1UewQN0VY9lZR94TX9j/GClK5BCDs5/D7FaHtlPoTDCvVN8lOpnpFd0LdgMn2LbN8vzvTKu+ujGmjJJiV9qMhYuXmFlGiJiNCkpY/wlO2+3/4TePQzU7xOV3YhchV3h7VWXHLGZIXH95a6nkoI5sL11oxIMoe3guVYgYG3UydvAqGbzwPlfbBZTxXaZduG3gaHdRrASKY6xzo1j9i8pM+jp0sgamvs3giVWKfpG90S+tEu2Ztmo9wX2HoUqp6ojY4tzC2oPJrS7LLLH8A40jwIDAQAB',
            'private_key' => 'MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCm1RTC4BhSpWAhqkz7nVb+pas4Mz6+TBOnIsHuVooBll4K4b8PMtu6pYqAc0WSZHEedRWBfZLXQDkKirSFRYN+6ji7sfBrvaus6D5fYNzN+4xj2vhOLsd3luYi4D4mWSaoxFvkgybnCLsRk6KmX5Fp8ML8datiZjUHXuuhBjBhZcKW/I+6De94UCXig+kVnWvKd7/EZuYJMAlQHvQ4ti0qEqaoFrNvM3/gBprHQO+V2NvuZhdFEvJ1jDq3LlKL53R+Hp5Wc0L8K+6wcMUtSoq7MlDV0NcQ8SZeAVqSRh0ERiI09MDM4hCwoxlS+bspX/qy712PpgRvMqXhJgDgZSUdAgMBAAECggEBAIVp1x10Sd8lovepEcERdPVVFNRvnphdjEXXNNDdYaWdUv1OxBRqbm8XXOgVxqgoLJHXvef8vMXn9PWqMGx3R43hzpbC2GnAlx5B50cs1cbfh8h+3pzfKeJHyShQvUK7fn/t7zKRczXEtJx8vNBhko7u2286xmB9LaEEVlhB88SeageElrz9BDARXiJjlNlhYLV8sYjWTY9G8+sfztZTpANN8PB97e9uMnZAP8yBl5/5YAjOeFusJzen06jvVUQ8xqOBb6Z3n/apsoE2OIYOqSSWJv4KNDAEdW9q+vVN4yhpskRs6Sb+NNu5pgme9yhzAoo20ahWl3rU0PvTuiJPSiECgYEA2VXspcWLvyatx0SP6c3/qRp5vysv/FMPqE6Ywv0o6G9X1M0EiqDiKWiArrxWSF3gk7hEWfGexr4/aaIxUVAsINkX3Ja2w62v5sThT0MOYY56tpgyeyfEzEXustZ2nexWGT7K2RvAQvwmmYUk6S4nU7DK8ucCpdt0iwstooL64akCgYEAxIMYRnF6k9znI8NRNv6M6bJuvDhwwo7dsVBxKf9vG+OZlBZOzOJ7HyQdOBuThmGWTjp8h6XV/w+4z2DfGZcfm/6rVHcKoBJK4rWTlaT0e36d5shHRPTtbjHron2yrzr3WpGmtwlMYQHQF26nXVzto4UGXyoUkn+7zNggMENpeFUCgYEAjttB8D0HfKAp/h99EUwMztTOTfBPXGYklpcDJrhNWWtGqmQQpibWQi2k2DaH6I18ftzSYOTHXw/Skta/4Bj4yKaqXp7ah4j1ZJTpHLaRD2MeGkO0eutLGpKlMfxyf5/HgFSb9VWebOldXe/8sSFbTFGbNUrPnMHBu1ufpYC+8/ECgYBUhX4/bjemuXDBNRUNblb1fUWbtzros8Iurca+pZsIh9BanW2vOgpyznmy1EmTlw2rAATn4zAz0HNQ3v2WaCW0VskiP0FWsAd9k1OzHYv6Qe9wf9wHkME+kEIlVaMxM0+IqPTn7Rvo7XqvWWyq/3lGx8SB0fufN0lzRdIycAxBMQKBgQCdnovZU+rSCzTHhvNAWMXqCizy6s9BJOQishrVhGi9OG2vjA+Om6tKmVX8EbnSM4+VzBBnAvEE3gERxCN9HwhPR0KTVjjX2Q5947UZCbRvyXkco8SI03JO27frDQoSEvo4Aj0K8oIeS3hiCqJyXMkIUm5GqpZHFBgU2Npa9wq7Gg==',
            'log' => '0',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '支付宝参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'epay',
        'title' => '易支付',
        'type' => 'array',
        'content' => [],
        'value' => [
            'api' => 'http://jzjxxy.xyz/',
            'pid' => '1000',
            'key' => 'd9x5kVr5RKD7622DS57awWd62Wko6DAx',
            'notify_url' => '/addons/epay/api/notifyx/type/epay',
            'return_url' => '/addons/epay/api/returnx/type/epay',
            'log' => '0',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '易支付参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'alipay_way',
        'title' => '支付宝通道选择',
        'type' => 'select',
        'content' => [
            'epay' => '易支付',
            'alipay' => '官方',
        ],
        'value' => 'epay',
        'rule' => 'required',
        'msg' => '',
        'tip' => '支付宝支付通道选择',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'wechat_way',
        'title' => '微信通道选择',
        'type' => 'select',
        'content' => [
            'epay' => '易支付',
            'wechat' => '官方',
        ],
        'value' => 'epay',
        'rule' => 'required',
        'msg' => '',
        'tip' => '微信支付通道选择',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => '__tips__',
        'title' => '温馨提示',
        'type' => 'array',
        'content' => [],
        'value' => '请注意微信支付证书路径位于/addons/epay/certs目录下，请替换成你自己的证书<br>'."\n"
            .'appid：APP的appid<br>'."\n"
            .'app_id：公众号的appid<br>'."\n"
            .'app_secret：公众号的secret<br>'."\n"
            .'miniapp_id：小程序ID<br>'."\n"
            .'mch_id：微信商户ID<br>'."\n"
            .'key：微信商户支付的密钥',
        'rule' => '',
        'msg' => '',
        'tip' => '微信参数配置',
        'ok' => '',
        'extend' => '',
    ],
];
